---
- name: Deploy Scientific Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Disable SSH host key checking
      set_fact:
       ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Pull Docker Image
      docker_image:
        name: "saki2726/scientific-calculator"
        source: pull

    - name: Remove existing container (if running)
      shell: docker rm -f scientificCalculator
      ignore_errors: yes

    - name: Run Docker Container
      shell: docker run -it -d --name scientificCalculator saki2726/scientific-calculator